export const lightTheme = {
  body: '#FFF',
  text: '#FAFAFA',
  inputText: '#363537',
  toggleBorder: '#FFF',
  background: '#363537',
  inputBackground: '#c9c9c9',
  textAreaBackground: '#f6f9fa',
  navBarBackground: '#f6f9fa',
  mainFieldBackground: '#f6f9fa',
  loginButtonBackground: '#fff',
  sendMessageBoardBackground: '#f6f9fa',
  sendButtonBackground: '#1e48e3',
  sendMessageBackground: '#1e48e3',
}

export const darkTheme = {
  body: '#363537',
  text: '#FAFAFA',
  inputText: '#363537',
  toggleBorder: '#6B8096',
  background: '#999',
  inputBackground: '#e8e8e8',
  textAreaBackground: '#f0f3fc',
  navBarBackground: '#f0f3fc',
  mainFieldBackground: '#f6f9fa',
  loginButtonBackground: '#fff',
  sendMessageBoardBackground: '#f0f3fc',
  sendButtonBackground: '#3653bf',
  sendMessageBackground: '#3653bf',
}